@BankTransfer_HostAddress = http://localhost:5105

GET {{BankTransfer_HostAddress}}/account/
Accept: application/json

###

POST {{BankTransfer_HostAddress}}/account/register
Accept: application/json

###

POST {{BankTransfer_HostAddress}}/account/login
Accept: application/json

###

POST {{BankTransfer_HostAddress}}/account/transfer
Accept: application/json