@BankTransfer_HostAddress = http://localhost:5105

GET {{BankTransfer_HostAddress}}/Account/
Accept: application/json

###

POST {{BankTransfer_HostAddress}}/Account/Register
Accept: application/json

###

POST {{BankTransfer_HostAddress}}/Account/Login
Accept: application/json

###

POST {{BankTransfer_HostAddress}}/Account/TransferMoney
Accept: application/json